### ISSUE TITLE
Cannot access  https://tdotdat.york.ac.uk

### ISSUE THREAD

**Issue by ajaycj1** [PlasmaFAIR/TDotDat#10]
Error message:
"503 Service Unavailable
No server is available to handle this request."

**Comment by ZedThree** [comment]
Oh dear, thanks for the heads up, I don't have any kind of monitoring set up yet!

Looks like it's having a bit of an issue, I'll sort it out and let you know when it's back up

**Comment by ZedThree** [comment]
Ok, that was really a lot of faff, but it's back up now!
